### ISSUE TITLE
Adding preRoll Ads does not seems to be working properly

### ISSUE THREAD

**Issue by Azokah** [SidKH/react-azure-mp#16]
Hello !
I have been trying to set a PreRoll Ad using this wrapper, but have been unable to. A little sample of the logic that im tryin to add would be:

```
ampAds:{
    preRoll: {
        sourceUri: 'http://sr-test.azurewebsites.net/Plugins/AMP2/Preroll_amp/vast_test.xml',
        options: 
        {
            skipAd: 
            {
                enabled: true,
                offset:5
            }
        }                                
    }
}
```

Am i doing something wrong? Is this something you can expose?
Already tried with a different number of options, including setting the [AdElement](http://amp.azure.net/libs/amp/latest/docs/index.html#amp.adelement)

**Comment by SidKH** [comment]
Hey, thanks for creating an issue.
The issue is reproducible with the vanilla js approach https://codesandbox.io/s/cocky-turing-vpt1j. No ads are loading.
  
So `react-azure-mp` is not what causes a problem, seems like `ampAds` options just don't work with azure media player.

I didn't find much documentation on `ampAds` except for [this article](https://azure.microsoft.com/en-us/blog/monetizing-your-content-with-azure-media-player/). They have a demo in the article that supposed to have ads but it also doesn't work. So I assume they either removed this option or renamed it.

**Comment by Azokah** [comment]
There is not a ton of information on the topic, the [only example](http://amp.azure.net/libs/amp/latest/samples/dynamic_vast_ads_vod.html) (exctracted from: [https://amp.azure.net/libs/amp/latest/docs/samples.html](https://amp.azure.net/libs/amp/latest/docs/samples.html)) i could find with working Ads was not reproducible, not even using the same code. 

I agree that it seems that react-azure-mp is not the issue here.
Thanks for your help !
