### ISSUE TITLE
Azure media player resets on render()

### ISSUE THREAD

**Issue by LTrain** [SidKH/react-azure-mp#27]
Is there a way to stop the Azure video player from resetting video playback to zero on a render? I've included an example of the problem.

Example:
https://codesandbox.io/s/azure-media-playback-sandbox-cmxy7?file=/src/App.js

**Comment by SidKH** [comment]
Hey, thanks for creating an issue and providing an example.
Working on the fix.

**Comment by SidKH** [comment]
Okay, here's what's happening:

The player only resets when `src` prop changes. 
It is intended behavior because in this case, we want to try to load new `src`

Since the format of `src` required by Azure is an array, it's easy to fall into trap of creating a new array on every render like that
```javascript
<AzureMP src={[{src: "//amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest",type: "application/vnd.ms-sstr+xml"}]} />
```

But if you don't want `src` prop to change on every render you have to memorize it, or put it into state:
```javascript
const src = useMemo(() => [{src: "//amssamples.streaming.mediaservices.windows.net/3b970ae0-39d5-44bd-b3a3-3136143d6435/AzureMediaServicesPromo.ism/manifest",type: "application/vnd.ms-sstr+xml"}], [])
return (
  <AzureMP src={src} />
)
```

Here is an updated version of your example with `src` in the state
https://codesandbox.io/s/azure-media-playback-sandbox-forked-42utu?file=/src/App.js

If you don't like to store `src` in state, you can simply define it above component so it doesn't change on every re-render as so
https://codesandbox.io/s/azure-media-playback-sandbox-forked-szxbb?file=/src/App.js

Let me know if it solves your problem.

**Comment by LTrain** [comment]
Oh! Very subtle – thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by LTrain** [comment]
Confirming this fixed the problem. We were passing in an array but that array was being dynamically generated every time we called render.  I moved that object into the state of the parent and the media works perfectly now. Thank you for your timely assistance.
